analyzer:
  clearOnStart: true
  source:
    resource: "/beans.json"
  rules:
    labels:
      type:
        Repository: '.*Repository'
        Controller: '.*Controller'
        Service: '.*Service'
        Configuration: '.*Configuration'
        App: 'com.example\\..*'
      name:
        Service: '.*Service'
      scope:
        Singleton: 'singleton'

spring:
  data:
    neo4j:
      uri: "bolt://192.168.99.100:7687"
      username: "neo4j"
      password: "admin"
